"""The nftables ruleset generator.

This is the security boundary. Read the forward chain below and convince
yourself of one claim:

    A packet that entered on the client bridge can leave this machine only
    through an interface named in @tun_ifaces.

Three independent rules enforce it, and none of them depends on the routing
table being correct, on the daemon being alive, or on a tunnel actually being
up. If all three were somehow bypassed, the chain policy is still ``drop``.

There is deliberately no per-destination exception mechanism - no split
tunnelling, no bypass list. Adding one would turn the guarantee above into "no
leak except through the hole", which cannot be audited at a glance and cannot
be asserted by the leak test. See docs/killswitch.md for the full reasoning.
Traffic that must not go through a VPN belongs on a machine that is not behind
this gateway.

The routing layer (see net/routing.py) adds a fourth, independent guarantee in
the kernel's FIB. The kill switch is not a feature that can be switched off;
it is the shape of the ruleset.
"""

from __future__ import annotations

from ..config import Settings
from ..models import Client, EgressKind, Pool, Tunnel

HEADER = """\
#!/usr/sbin/nft -f
#
# GENERATED BY vpngw - DO NOT EDIT.
# Edits are lost on the next reconcile. Change /etc/vpngw/vpngw.toml or use
# vpngwctl / the web UI instead.
#
# The create-delete-define idiom below makes the swap a single transaction:
# there is no instant at which this table is missing or permissive.

table inet vpngw
delete table inet vpngw
"""


def _elements(values) -> str:
    """Render an ``elements = { ... }`` line, or nothing when empty.

    nftables rejects ``elements = { }``, and an empty set is the normal state
    on a fresh install, so this has to be handled rather than special-cased at
    every call site.
    """
    values = list(values)
    if not values:
        return ""
    body = ", ".join(str(v) for v in values)
    return f"        elements = {{ {body} }}\n"


def render(
    settings: Settings,
    tunnels: list[Tunnel],
    pools: list[Pool],
    clients: list[Client],
    *,
    maintenance: bool = False,
    api_endpoints: list[str] | None = None,
) -> str:
    net = settings.net
    dns = settings.dns

    lan = net.lan_bridge
    wan = net.wan_iface
    # Management reaches this box one of two ways, and never over the client
    # bridge: either a dedicated interface, or the uplink restricted to one
    # source range. Settings.validate() refuses to start when neither is set,
    # because applying this ruleset with no management path is unrecoverable
    # over the network - by design, nothing else is listening.
    mgmt = net.mgmt_iface

    enabled_tunnels = [t for t in tunnels if t.enabled]
    tun_ifaces = [f'"{t.iface}"' for t in enabled_tunnels]
    client_ifaces = [f'"{i}"' for i in net.client_interfaces()]

    # esid lookup so a client can be resolved to its egress in one pass
    esid_by_egress: dict[tuple[EgressKind, str], int] = {}
    for t in enabled_tunnels:
        esid_by_egress[(EgressKind.TUNNEL, t.slug)] = t.esid
    for p in pools:
        if p.enabled:
            esid_by_egress[(EgressKind.POOL, p.slug)] = p.esid

    cli2mark: list[str] = []
    cli2dns: list[str] = []
    for c in clients:
        if not c.enabled or not c.egress_slug:
            continue  # unassigned clients fall through to unclassified_drop
        esid = esid_by_egress.get((c.egress_kind, c.egress_slug))
        if esid is None:
            continue  # egress disabled: same as unassigned, traffic is dropped
        cli2mark.append(f"{c.ip} : {esid:#06x}")
        cli2dns.append(f"{c.ip} : {dns.resolver_ip(esid)}")

    endpoints = sorted({ep for t in enabled_tunnels for ep in t.endpoints})
    resolver_net = dns.resolver_subnet

    out: list[str] = [HEADER]
    a = out.append

    a(f"""
define WAN  = "{wan}"
define LAN  = "{lan}"
define LAN_NET      = {net.lan_network}
define RESOLVER_NET = {resolver_net}
""")
    if mgmt:
        a(f'define MGMT = "{mgmt}"\n')
    a("\ntable inet vpngw {\n")

    # -- named counters -----------------------------------------------------
    a("""\
    # Named counters double as the audit trail. `vpngwctl selftest` asserts on
    # wan_leak_drop specifically: if a client ever tries to escape unencrypted,
    # this counter is where the attempt is recorded.
    counter wan_leak_drop      { comment "forwarded traffic aimed at the uplink" }
    counter nontunnel_drop     { comment "forwarded traffic aimed at a non-tunnel" }
    counter unclassified_drop  { comment "client with no egress assigned" }
    counter invalid_drop       { comment "conntrack-invalid forwards" }
    counter forwarded_new      { comment "new client flows admitted to a tunnel" }
    counter returned           { comment "tunnel to client replies" }
    counter input_drop         { comment "unsolicited traffic to the gateway" }
    counter host_egress_drop   { comment "the gateway's own blocked egress" }
    counter dns_hijacked       { comment "client DNS queries redirected" }

""")

    # -- sets and maps ------------------------------------------------------
    a("    set tun_ifaces {\n        type ifname\n")
    a("        comment \"the only interfaces forwarded traffic may leave by\"\n")
    a(_elements(tun_ifaces))
    a("    }\n\n")

    # Which interfaces count as facing clients. Normally just the LAN bridge.
    # Adding the uplink here supports clients that share the uplink's subnet and
    # point their default route at this box - the forward chain treats them
    # identically, so a registered client is still confined to its tunnel.
    a("    set client_ifaces {\n        type ifname\n")
    a("        comment \"interfaces client traffic is accepted from\"\n")
    a(_elements(client_ifaces))
    a("    }\n\n")

    a("    set vpn_endpoints {\n        type ipv4_addr\n        flags interval\n")
    a("        comment \"remote VPN servers the gateway itself may dial\"\n")
    a(_elements(endpoints))
    a("    }\n\n")

    a("    set bootstrap_dns {\n        type ipv4_addr\n")
    a("        comment \"resolvers used only to look up endpoint hostnames\"\n")
    a(_elements(dns.bootstrap))
    a("    }\n\n")

    # Empty until a provider account is configured, so a default install has no
    # hole for an API it never calls. Populated by the reconciler from the
    # declared api_hosts of enabled providers only - never from whatever a
    # plugin decides to fetch.
    a("    set provider_api {\n        type ipv4_addr\n")
    a("        comment \"API hosts of configured VPN providers\"\n")
    a(_elements(api_endpoints or ()))
    a("    }\n\n")

    a("    map cli2mark {\n        type ipv4_addr : mark\n")
    a("        comment \"client address -> egress selector\"\n")
    a(_elements(cli2mark))
    a("    }\n\n")

    a("    map cli2dns {\n        type ipv4_addr : ipv4_addr\n")
    a("        comment \"client address -> its egress's resolver\"\n")
    a(_elements(cli2dns))
    a("    }\n\n")

    # -- classification -----------------------------------------------------
    a("""\
    chain mangle_prerouting {
        type filter hook prerouting priority mangle; policy accept;

        # Only client-originated traffic needs an egress selector. Marking
        # replies arriving from a tunnel would send them straight back out of
        # that tunnel instead of to the client, so bail out early.
        iifname != @client_ifaces return

        # Classification is stateless: the source address is looked up on every
        # packet, so a reassignment in the UI takes effect immediately rather
        # than when the flow happens to expire.
        meta mark set ip saddr map @cli2mark

        # Mirrored onto the conntrack entry purely so that failover can flush
        # the affected flows with `conntrack -D -m <mark>`.
        ct mark set meta mark
    }

""")

    # -- path MTU ----------------------------------------------------------
    a("""\
    chain mangle_forward {
        type filter hook forward priority mangle; policy accept;

        # Clamp TCP MSS to the tunnel's path MTU.
        #
        # Without this the symptom is specific and misleading: a client
        # negotiates a 1460-byte MSS against a 1380-byte tunnel, so small
        # exchanges succeed and anything larger silently stalls. DNS works,
        # pings work, web pages hang half-loaded - and every layer looks
        # healthy while you are debugging it.
        #
        # Path MTU discovery is supposed to fix this by itself, but it relies
        # on ICMP "fragmentation needed" getting back to the client, which on
        # the public internet it frequently does not. Clamping does not depend
        # on anybody else's ICMP.
        oifname @tun_ifaces tcp flags syn / syn,rst \\
            tcp option maxseg size set rt mtu
    }

""")

    # -- forward: the kill switch ------------------------------------------
    a("""\
    chain forward {
        type filter hook forward priority filter; policy drop;

        # Return path. Conntrack proves these belong to a flow this chain
        # already admitted outbound, so they are not an inbound probe.
        iifname @tun_ifaces oifname @client_ifaces ct state established,related \\
            counter name "returned" accept

        # ------------------------------------------------------------------
        # KILL SWITCH. Everything past this point is client -> internet.
        # ------------------------------------------------------------------

        # 1. Never the uplink. Not when a tunnel is down, not while one is
        #    reconnecting, not during a reconcile, not at boot.
        oifname $WAN counter name "wan_leak_drop" drop

        # 2. Never anything else either - a second uplink, a bridge added by
        #    hand, an interface that did not exist when this was written.
        #    Allow-list, not deny-list.
        oifname != @tun_ifaces counter name "nontunnel_drop" drop

        ct state invalid counter name "invalid_drop" drop

        # 3. Established client flows, already vetted by the rules below.
        iifname @client_ifaces oifname @tun_ifaces ct state established,related accept

        # 4. New client flows: must carry an egress selector. A client that is
        #    unknown, disabled, or assigned to a disabled egress has mark 0 and
        #    falls through to the drop at the end.
        iifname @client_ifaces oifname @tun_ifaces meta mark != 0x0 ct state new \\
            counter name "forwarded_new" accept

        counter name "unclassified_drop" drop
    }

""")

    # -- input --------------------------------------------------------------
    a("""\
    chain input {
        type filter hook input priority filter; policy drop;

        iif lo accept
        ct state invalid drop
        ct state established,related accept

        # Path MTU discovery. Without this, tunnels appear to work until the
        # first large packet and then hang, which is a miserable way to spend
        # an afternoon.
        icmp type { destination-unreachable, time-exceeded, parameter-problem } accept
""")
    a("\n        # Management plane.\n")
    for iface in net.management_ifaces():
        a(f"""        # Management is a property of which side of the box you stand on, not
        # of your source address. The uplink appears here only if the operator
        # added it to admin_ifaces themselves.
        iifname "{iface}" tcp dport {{ 22, {settings.api.port} }} accept
        iifname "{iface}" icmp type echo-request accept
""")
    a("""\

        # Clients: DNS to their own hijacked resolver, and ping to the gateway
        # for diagnostics. Nothing else - not SSH, not the web UI.
        iifname @client_ifaces ip daddr $RESOLVER_NET udp dport 53 accept
        iifname @client_ifaces ip daddr $RESOLVER_NET tcp dport 53 accept
        iifname @client_ifaces icmp type echo-request accept

        counter name "input_drop" drop
    }

""")

    # -- output -------------------------------------------------------------
    if settings.killswitch.strict_host_egress and not maintenance:
        a("""\
    chain output {
        type filter hook output priority filter; policy drop;

        oif lo accept
        ct state established,related accept

        # The gateway may dial the VPN servers it was configured with, and
        # nothing else on the uplink. @vpn_endpoints is populated from the
        # imported tunnel configs and refreshed when a hostname's address
        # changes.
        oifname $WAN ip daddr @vpn_endpoints accept

        # Resolving those endpoints, before any tunnel exists to resolve
        # through. Restricted to the bootstrap resolvers.
        oifname $WAN ip daddr @bootstrap_dns udp dport 53 accept
        oifname $WAN ip daddr @bootstrap_dns tcp dport 53 accept

        # Provider APIs, so a configured account can list servers and register
        # keys. Empty unless a provider account exists, and limited to HTTPS.
        oifname $WAN ip daddr @provider_api tcp dport 443 accept

        # DHCP on the uplink, and NTP: OpenVPN's TLS handshake fails outright
        # on a skewed clock, and a VM that has been paused is always skewed.
        oifname $WAN udp sport 68 udp dport 67 accept
        oifname $WAN udp dport 123 accept
        oifname $WAN icmp type { echo-request, echo-reply } accept

        # Health probes, per-egress resolvers, anything else we send into a
        # tunnel. Safe by construction: it is encrypted.
        oifname @tun_ifaces accept

""")
        if mgmt:
            a("        oifname $MGMT accept\n")
        a("""\
        oifname $LAN accept

        counter name "host_egress_drop" drop
    }

""")
    else:
        reason = "maintenance window open" if maintenance else "strict_host_egress = false"
        a(f"""\
    chain output {{
        type filter hook output priority filter; policy accept;
        # {reason} - the gateway's own traffic is unrestricted.
        # Client traffic is unaffected: the forward chain above is untouched.
        oifname $WAN counter name "host_egress_drop" accept
    }}

""")

    # -- nat ----------------------------------------------------------------
    a("""\
    chain nat_prerouting {
        type nat hook prerouting priority dstnat; policy accept;

        # DNS interception. The clients use static addresses, so nothing hands
        # them a resolver and any of them could be pointed at 8.8.8.8 by hand.
        # Every :53 query is redirected to the resolver bound to that client's
        # own egress, whose upstream traffic is itself confined to the tunnel.
        # A client cannot opt out of this.
""")
    a("""\
        iifname @client_ifaces udp dport 53 counter name "dns_hijacked" \\
            dnat ip to ip saddr map @cli2dns
        iifname @client_ifaces tcp dport 53 dnat ip to ip saddr map @cli2dns
    }

    chain nat_postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        oifname @tun_ifaces masquerade
    }
""")

    if dns.block_dot:
        a("""
    chain block_dot {
        type filter hook forward priority filter - 10; policy accept;
        # Optional: stop clients using DNS-over-TLS so that every lookup is
        # visible to (and filterable by) the gateway's resolver. The traffic
        # would still be inside the tunnel, so this is a control preference,
        # not a leak fix.
        iifname @client_ifaces tcp dport 853 reject with tcp reset
    }
""")

    a("}\n")
    return "".join(out)


# ---------------------------------------------------------------------------
# boot-time skeleton
# ---------------------------------------------------------------------------


def render_killswitch(settings: Settings) -> str:
    """The ruleset loaded before the network comes up.

    Ordered ``Before=network-pre.target`` by its systemd unit, so between the
    kernel bringing interfaces up and vpngw finishing its first reconcile, the
    box is already refusing to forward. There is no permissive window at boot,
    which is the one hole most hand-rolled kill switches leave open.
    """
    net = settings.net

    # The skeleton has to keep the same administrative door open that the full
    # ruleset does. If it did not, a boot where vpngw fails to start would be
    # unreachable - fail-closed for clients is correct, but locking the
    # operator out of a box that needs fixing is just a brick.
    admin_rules = []
    for iface in net.management_ifaces():
        admin_rules.append(
            f'        iifname "{iface}" tcp dport {{ 22 }} accept'
        )
    admin_block = "\n".join(admin_rules) or (
        "        # no management path configured - see [net] in vpngw.toml"
    )

    return f"""\
#!/usr/sbin/nft -f
#
# vpngw boot-time fail-closed skeleton.
#
# Loaded before network-pre.target. If vpngw never starts - unit masked,
# database corrupt, Python broken by a bad upgrade - the box stays in this
# state and forwards nothing. Failure of the control plane is not a leak.

table inet vpngw
delete table inet vpngw

table inet vpngw {{
    counter wan_leak_drop     {{ comment "boot skeleton: uplink" }}
    counter nontunnel_drop    {{ comment "boot skeleton: non-tunnel" }}
    counter unclassified_drop {{ comment "boot skeleton: unclassified" }}

    chain forward {{
        type filter hook forward priority filter; policy drop;
        oifname "{net.wan_iface}" counter name "wan_leak_drop" drop
        counter name "unclassified_drop" drop
    }}

    chain input {{
        type filter hook input priority filter; policy drop;
        iif lo accept
        ct state established,related accept
{admin_block}
        icmp type echo-request accept
    }}

    chain output {{
        type filter hook output priority filter; policy accept;
    }}
}}
"""
