"""Changing the uplink's address without losing the machine.

This is the one setting that can cut off the connection you are using to change
it. Get it wrong on a box in another building and the only fix is physical.

So it is applied the way network equipment has done it for decades: write the
new configuration, arm a timer that restores the old one, apply, then prove the
box is still reachable. If the proof fails - or if nobody confirms in time -
the timer fires and the machine comes back on its old address by itself.

The confirmation is deliberately a separate step. An apply that verifies itself
can only check what it thought to check; a human confirming means the path that
actually matters was tested, because they used it.
"""

from __future__ import annotations

import ipaddress
import logging
import time
from pathlib import Path

from .shell import run, try_run

log = logging.getLogger("vpngw.apply")

IFUPDOWN_FILE = Path("/etc/network/interfaces.d/vpngw-wan")
NETWORKD_FILE = Path("/etc/systemd/network/20-wan0.network")
BACKUP_DIR = Path("/var/lib/vpngw/netbackup")
ROLLBACK_UNIT = "vpngw-netrollback"
DEADLINE_FILE = BACKUP_DIR / "deadline"


class ApplyError(RuntimeError):
    """Refused before anything changed, or rolled back after it did."""


def stack() -> str:
    """Which service owns the interfaces on this box."""
    if try_run(["systemctl", "is-enabled", "systemd-networkd"]).stdout.strip() == "enabled":
        return "networkd"
    if try_run(["systemctl", "is-enabled", "networking"]).stdout.strip() == "enabled":
        return "ifupdown"
    return "networkd"


# ---------------------------------------------------------------------------
# validation
# ---------------------------------------------------------------------------


def validate_wan(mode: str, address: str, gateway: str) -> None:
    """Reject what cannot work, before touching anything.

    The check that matters is the last one: a gateway outside the address's own
    subnet is unreachable, so the box would come up with an address and no way
    off it. That mistake is easy to make and impossible to fix remotely.
    """
    if mode not in ("dhcp", "static"):
        raise ApplyError(f"unknown mode {mode!r}")
    if mode == "dhcp":
        return

    try:
        iface = ipaddress.ip_interface(address)
    except ValueError as exc:
        raise ApplyError(f"{address!r} is not an address with a prefix: {exc}")
    if iface.network.prefixlen > 30:
        raise ApplyError("the prefix leaves no room for a gateway")
    if not gateway:
        raise ApplyError("a static uplink needs a gateway")
    try:
        gw = ipaddress.ip_address(gateway)
    except ValueError as exc:
        raise ApplyError(f"{gateway!r} is not an address: {exc}")
    if gw not in iface.network:
        raise ApplyError(
            f"the gateway {gw} is not inside {iface.network}. The box would "
            f"come up with an address and no route off it, and on a remote "
            f"machine that is unrecoverable."
        )
    if gw == iface.ip:
        raise ApplyError("the gateway cannot be the machine's own address")


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------


def render_ifupdown(iface: str, mode: str, address: str, gateway: str,
                    dns: list[str]) -> str:
    lines = [
        "# GENERATED BY vpngw - do not edit; use the panel or vpngwctl.",
        f"auto {iface}",
    ]
    if mode == "dhcp":
        lines.append(f"iface {iface} inet dhcp")
    else:
        lines += [
            f"iface {iface} inet static",
            f"    address {address}",
            f"    gateway {gateway}",
        ]
        if dns:
            lines.append(f"    dns-nameservers {' '.join(dns)}")
    return "\n".join(lines) + "\n"


def render_networkd(iface: str, mode: str, address: str, gateway: str,
                    dns: list[str]) -> str:
    lines = ["# GENERATED BY vpngw - do not edit.", "[Match]",
             f"Name={iface}", "", "[Network]"]
    if mode == "dhcp":
        lines.append("DHCP=ipv4")
    else:
        lines.append(f"Address={address}")
        lines.append(f"Gateway={gateway}")
        for server in dns:
            lines.append(f"DNS={server}")
    lines += ["LinkLocalAddressing=no", "IPv6AcceptRA=no"]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# apply
# ---------------------------------------------------------------------------


def _target() -> Path:
    return NETWORKD_FILE if stack() == "networkd" else IFUPDOWN_FILE


MAIN_INTERFACES = Path("/etc/network/interfaces")
TAKEOVER_MARK = "#vpngw-disabled# "


def _snapshot(paths: list[Path]) -> Path:
    """Copy each file into a timestamped directory and record where it came from.

    A manifest rather than a single file because taking over the uplink can
    touch two: the drop-in this module owns, and the distribution's own
    interfaces file, whose conflicting stanza has to be disabled. Restoring one
    without the other would leave the interface defined twice or not at all.
    """
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    snap = BACKUP_DIR / str(int(time.time()))
    snap.mkdir(parents=True, exist_ok=True)
    manifest = []
    for index, path in enumerate(paths):
        copy = snap / f"{index}.file"
        copy.write_text(path.read_text() if path.exists() else "")
        manifest.append(f"{index}\t{path}")
    (snap / "manifest").write_text("\n".join(manifest) + "\n")
    (BACKUP_DIR / "latest").write_text(str(snap))
    return snap


def restore_snapshot(snap: Path) -> None:
    """Put every file in a snapshot back where it came from."""
    manifest = snap / "manifest"
    if not manifest.exists():
        raise ApplyError(f"{snap} has no manifest")
    for line in manifest.read_text().splitlines():
        if not line.strip():
            continue
        index, dest = line.split("\t", 1)
        Path(dest).write_text((snap / f"{index}.file").read_text())


def conflicting_stanza(iface: str, text: str) -> bool:
    """Does this file already define the interface we are about to define?"""
    for line in text.splitlines():
        head = line.strip().split()
        if len(head) >= 2 and head[0] in ("iface", "auto", "allow-hotplug")                 and iface in head[1:]:
            return True
    return False


def take_over_ifupdown(iface: str) -> bool:
    """Comment out the distribution's own stanza for the uplink.

    /etc/network/interfaces both defines eth0 and sources interfaces.d/*. Left
    alone, our drop-in becomes a second definition of the same interface:
    ifupdown keeps the first and ignores ours, so the address never moves while
    everything reports success. Disabling the original - reversibly, and
    snapshotted before the change - makes our file the only definition.
    """
    if not MAIN_INTERFACES.exists():
        return False
    text = MAIN_INTERFACES.read_text()
    if not conflicting_stanza(iface, text):
        return False

    out, inside = [], False
    for line in text.splitlines():
        head = line.strip().split()
        if head and head[0] in ("iface", "auto", "allow-hotplug", "source",
                                "mapping"):
            inside = (head[0] in ("iface", "auto", "allow-hotplug")
                      and iface in head[1:])
        elif not line.strip():
            inside = False
        out.append(TAKEOVER_MARK + line if inside else line)
    MAIN_INTERFACES.write_text("\n".join(out) + "\n")
    log.warning("disabled the existing %s stanza in %s; vpngw now owns it",
                iface, MAIN_INTERFACES)
    return True


def arm_rollback(snap: Path, minutes: int) -> None:
    """A timer that puts the old configuration back unless somebody confirms.

    Runs even if this process dies mid-apply, which is exactly the case it
    exists for: the apply is what breaks the connection this process is
    talking over.
    """
    cancel_rollback()
    # Plain shell, no interpreter. This has to run when the daemon is the
    # thing that is broken - a half-applied config, a package that no longer
    # imports - so it must not depend on any of it.
    script = (
        f"while read -r i dest; do "
        f"  cp \"{snap}/$i.file\" \"$dest\"; "
        f"done < \"{snap}/manifest\"; "
        f"systemctl restart networking 2>/dev/null; "
        f"systemctl restart systemd-networkd 2>/dev/null; "
        f"systemctl restart vpngw"
    )
    run([
        "systemd-run", f"--on-active={minutes}min", f"--unit={ROLLBACK_UNIT}",
        "/bin/sh", "-c", script,
    ])
    DEADLINE_FILE.parent.mkdir(parents=True, exist_ok=True)
    DEADLINE_FILE.write_text(f"{int(time.time() + minutes * 60)}\n")
    log.warning("rollback armed: the previous uplink config returns in %d "
                "minutes unless confirmed", minutes)


def cancel_rollback() -> None:
    try:
        DEADLINE_FILE.unlink()
    except OSError:
        pass
    try_run(["systemctl", "stop", f"{ROLLBACK_UNIT}.timer"])
    try_run(["systemctl", "reset-failed", f"{ROLLBACK_UNIT}.service"])
    try_run(["systemctl", "reset-failed", f"{ROLLBACK_UNIT}.timer"])


def rollback_now() -> None:
    """Restore the previous configuration immediately.

    The same work the timer would do, done on request - for the case where the
    operator can see the change was wrong and would rather not sit out the
    remaining minutes.
    """
    latest = BACKUP_DIR / "latest"
    if not latest.exists():
        raise ApplyError("there is no saved configuration to restore")
    snap = Path(latest.read_text().strip())
    if not snap.exists():
        raise ApplyError(f"the saved configuration {snap} is gone")

    cancel_rollback()
    restore_snapshot(snap)
    if stack() == "networkd":
        try_run(["systemctl", "restart", "systemd-networkd"], timeout=30)
    else:
        try_run(["systemctl", "restart", "networking"], timeout=30)
    time.sleep(2)
    try_run(["systemctl", "restart", "vpngw"], timeout=60)
    log.warning("previous uplink configuration restored")


def rollback_pending() -> bool:
    res = try_run(["systemctl", "is-active", f"{ROLLBACK_UNIT}.timer"])
    return res.stdout.strip() == "active"


def rollback_seconds_left() -> int:
    """Seconds until the timer fires. 0 if nothing is armed, -1 if unknown.

    Read from a deadline this module writes when it arms the timer, not from
    systemd. ``systemd-run --on-active`` creates a monotonic timer, so
    NextElapseUSecRealtime is empty and the monotonic figure comes back as
    prose ("15h 16min 31.366882s") that would have to be parsed against
    /proc/uptime. Recording the deadline is exact, survives a restart because
    it is on disk, and cannot drift from the timer because the same call
    writes both.

    The distinction between 0 and -1 matters to the panel: 0 hides the confirm
    banner, and hiding it while a change is genuinely on a timer would let a
    working configuration revert because nobody was told to keep it.
    """
    if not rollback_pending():
        return 0
    try:
        deadline = float(DEADLINE_FILE.read_text().strip())
    except (OSError, ValueError):
        return -1
    return max(0, int(deadline - time.time())) or -1


def apply_wan(iface: str, mode: str, address: str, gateway: str,
              dns: list[str], *, rollback_minutes: int = 5) -> dict:
    """Write and apply the uplink configuration, with a rollback armed first.

    Returns what happened. The caller is expected to confirm afterwards - see
    :func:`cancel_rollback` - and the change is not permanent until they do.
    """
    validate_wan(mode, address, gateway)

    target = _target()
    target.parent.mkdir(parents=True, exist_ok=True)

    # Both files are snapshotted, because taking over the interface may edit
    # the distribution's own as well, and restoring only one of the two would
    # leave the uplink defined twice or not at all.
    files = [target] + ([MAIN_INTERFACES] if stack() == "ifupdown" else [])
    snap = _snapshot(files)

    text = (render_networkd if stack() == "networkd" else render_ifupdown)(
        iface, mode, address, gateway, dns)

    # Armed *before* the change, not after: the apply is what cuts the
    # connection, so there may be no "after" in which to arm anything.
    arm_rollback(snap, rollback_minutes)

    took_over = False
    if stack() == "ifupdown":
        took_over = take_over_ifupdown(iface)
    target.write_text(text)

    if stack() == "networkd":
        try_run(["systemctl", "restart", "systemd-networkd"], timeout=30)
    else:
        # ifupdown cannot re-read an interface in place; down then up. Losing
        # the connection here is expected - that is what the rollback is for.
        try_run(["ifdown", iface], timeout=30)
        try_run(["ifup", iface], timeout=30)

    time.sleep(3)
    try_run(["systemctl", "restart", "vpngw"], timeout=60)

    return {
        "stack": stack(),
        "file": str(target),
        "backup": str(snap),
        "took_over_main_interfaces": took_over,
        "rollback_minutes": rollback_minutes,
        "reachable": verify(gateway if mode == "static" else ""),
    }


def verify(gateway: str = "") -> dict:
    """A best-effort look at whether the box still has a working uplink.

    Not proof. It cannot test the path the operator actually uses - only they
    can, by still being connected - which is why the rollback waits for a
    human rather than for this.
    """
    import json as _json

    out: dict = {"default_route": None, "gateway_reachable": None}
    res = try_run(["ip", "-json", "route", "show", "default"])
    try:
        routes = _json.loads(res.stdout or "[]")
        if routes:
            out["default_route"] = routes[0].get("gateway") or routes[0].get("dev")
    except ValueError:
        pass
    if gateway:
        out["gateway_reachable"] = try_run(
            ["ping", "-c", "1", "-W", "2", "-n", gateway], timeout=6).ok
    return out
